// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import data "github.com/ramadani/go-api-skeleton/app/user/data"
import mock "github.com/stretchr/testify/mock"

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: name, email, password
func (_m *Usecase) Create(name string, email string, password string) (data.User, error) {
	ret := _m.Called(name, email, password)

	var r0 data.User
	if rf, ok := ret.Get(0).(func(string, string, string) data.User); ok {
		r0 = rf(name, email, password)
	} else {
		r0 = ret.Get(0).(data.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(name, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *Usecase) Delete(id uint) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: id
func (_m *Usecase) FindByID(id uint) (data.User, error) {
	ret := _m.Called(id)

	var r0 data.User
	if rf, ok := ret.Get(0).(func(uint) data.User); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(data.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Paginate provides a mock function with given fields: page, limit
func (_m *Usecase) Paginate(page uint, limit uint) (data.UserPaginate, error) {
	ret := _m.Called(page, limit)

	var r0 data.UserPaginate
	if rf, ok := ret.Get(0).(func(uint, uint) data.UserPaginate); ok {
		r0 = rf(page, limit)
	} else {
		r0 = ret.Get(0).(data.UserPaginate)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, uint) error); ok {
		r1 = rf(page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: name, id
func (_m *Usecase) Update(name string, id uint) (data.User, error) {
	ret := _m.Called(name, id)

	var r0 data.User
	if rf, ok := ret.Get(0).(func(string, uint) data.User); ok {
		r0 = rf(name, id)
	} else {
		r0 = ret.Get(0).(data.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, uint) error); ok {
		r1 = rf(name, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
